[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmd = 'pnpm install'

[phases.build]
cmd = 'pnpm run build'

[start]
cmd = 'pnpm start'

[variables]
NODE_ENV = 'production'
PORT = '3000'