[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm_8']

[phases.install]
cmd = 'pnpm install --frozen-lockfile'

[phases.build]
cmd = 'pnpm run build'

[start]
cmd = 'pnpm start'

[variables]
NODE_ENV = 'production'
PORT = '3000'
NPM_CONFIG_PRODUCTION = 'false'